---
documentation:
  - changed-files:
      - any-glob-to-any-file: "README.md"

ops:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

plugin:
  - changed-files:
      - any-glob-to-any-file: "plugin/**/*"

component:
  - changed-files:
      - any-glob-to-any-file: "components/*"

widget:
  - changed-files:
      - any-glob-to-any-file: "components/widgets/**/*"

bar:
  - changed-files:
      - any-glob-to-any-file: "components/bar/**/*"

dashboard:
  - changed-files:
      - any-glob-to-any-file: "components/dashboard/**/*"

notifications:
  - changed-files:
      - any-glob-to-any-file: "components/notifications/**/*"

lockscreen:
  - changed-files:
      - any-glob-to-any-file: "components/lockscreen/**/*"

session:
  - changed-files:
      - any-glob-to-any-file: "components/session/**/*"

launcher:
  - changed-files:
      - any-glob-to-any-file: "components/Launcher.qml"

preferences:
  - changed-files:
      - any-glob-to-any-file: "components/Preferences.qml"

config:
  - changed-files:
      - any-glob-to-any-file: "Config.qml"

state:
  - changed-files:
      - any-glob-to-any-file: "States.qml"

wallpaper:
  - changed-files:
      - any-glob-to-any-file: "Wallpaper.qml"

util:
  - changed-files:
      - any-glob-to-any-file: "Utils.qml"

feature:
  - head-branch: ["^feature", "feature"]
