find_package(Git)

execute_process(
    COMMAND git status --porcelain
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_STATUS
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
    COMMAND git describe --tags --abbrev=0
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_LATEST_TAG
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE GIT_TAG_RESULT
)

execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    ERROR_QUIET
    OUTPUT_VARIABLE GIT_COMMIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT GIT_STATUS STREQUAL "")
    set(GIT_COMMIT_HASH "${GIT_COMMIT_HASH}-dirty")
endif()

set(GIT_VERSION "${GIT_LATEST_TAG}+${GIT_COMMIT_HASH}")

if(NOT GIT_TAG_RESULT EQUAL 0)
    set(GIT_LATEST_TAG "${PROJECT_VERSION}")
    set(GIT_VERSION "${PROJECT_VERSION}")
endif()

string(REGEX MATCH "^([0-9]+)\\.([0-9]+)\\.([0-9]+)" SEMVER_MATCHES "${GIT_LATEST_TAG}")

if(SEMVER_MATCHES)
    string(REGEX REPLACE "^([0-9]+)\\..*" "\\1" PROJECT_VERSION_MAJOR "${GIT_LATEST_TAG}")
    string(REGEX REPLACE "^[0-9]+\\.([0-9]+)\\..*" "\\1" PROJECT_VERSION_MINOR "${GIT_LATEST_TAG}")
    string(REGEX REPLACE "^[0-9]+\\.[0-9]+\\.([0-9]+).*" "\\1" PROJECT_VERSION_PATCH "${GIT_LATEST_TAG}")
endif()

set(VERSION "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}")

set(PROJECT_DISTRIBUTOR "${DISTRIBUTOR}")
set(PROJECT_PLATFORM "${PLATFORM}")
set(PROJECT_VERSION_FULL "${GIT_VERSION}")

message(STATUS "Setting ${PROJECT_VERSION_FULL}")

configure_file(
    ${CMAKE_SOURCE_DIR}/plugin/version.h.in
    ${CMAKE_BINARY_DIR}/plugin/version.h
    @ONLY
)
