---
name: CI
"on": [push, pull_request]

permissions:
  id-token: write
  contents: read
  attestations: read

jobs:
  release:
    name: Release
    permissions:
      contents: write
      id-token: write
      attestations: write
      pages: write

    if: |
      github.repository_owner == 'charlesrocket' &&
      startsWith(github.ref, 'refs/tags/')

    uses: ./.github/workflows/cd.yml
    with:
      tag_name: ${{ github.ref_name }}
